name: jofftest
favicon: null
layout_spectrum: 1
typography_spectrum: 0.12508
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000822'
    - '#b38086'
    - '#ecc6bf'
    - '#943564'
  brandStrength: 0.5502517779823393
  lightness: 0.9375
  saturation: 0.45272912783548236
  rhythmicContrast: 0.9631806374527514
purpose: []
